### ISSUE TITLE
Debug - Helper static function for nice type names

### ISSUE THREAD

**Issue by jkeon** [decline-cookies/anvil-csharp-core#112]
I've found I'm writing this all over the place:

```
m_TypeString = type.IsGenericType
                ? $"{type.Name[..^2]}<{type.GenericTypeArguments[0].Name}>"
                : type.Name;
```

I want to nicely output logs with the type of object I'm working with but I don't want to see the fully qualified class name all the time as it's tricky to read. 

Instead of `Anvil.Unity.DOTS.Entities.ProxyDataStream\`, `DeclineCookies.TwistedDots.Game.Simulation.TimerInstance`

I'd like to see it like you would in code with `ProxyDataStream<TimerInstance>`

The above example assumes only one generic type so we should have a general solution that adds the comma separators for N types. 

`MainType<GType1, GType2, GType3, GTypeN>`

**Comment by mbaker3** [comment]
Is this for incorporating a type other than the calling type name into a log string? Curious if `Logger` currently captures a good name for generics.

**Comment by jkeon** [comment]
I have a class that's a `EntityProxyDataStream<TimerInstance>`. 

When i look at the `Type` for that its:

`Anvil.Unity.DOTS.Entities.Tasks.EntityProxyDataStream``1[DeclineCookies.TwistedDots.Game.Simulation.TimerInstance]`

Which is a mouthful and makes the logs really polluted. 

But if I just do `Type.Name` I get: 

`EntityProxyDataStream``1`

What I really want is how I would see it in the code as `EntityProxyDataStream<TimerInstance>` and this accomplishes that.

The logs are clean and easier to parse.

**Comment by mbaker3** [comment]
Is that what it looks like in the context that logger generates as well though? Ex: what's in the {myType} part of the log message in this example when logging?
`({myType}|MyMethod:0) Some message`

Just trying to figure out if the solution needs to be applied to logger as well or if logger provides a better result that we can steal the approach from. Having to resolve the and format the type string at runtime isn't ideal.

**Comment by jkeon** [comment]
Ah sorry, I see, I hadn't checked. All my "logs" were being thrown as exceptions so they weren't going through Logger.

Just did a quick test and I get this:

`(EntityProxyDataStream|.ctor:33) Test`

So it does appear that some work needs to be done in Logger to accommodate the generics part since that's not being included.

**Comment by mbaker3** [comment]
ok, good to know. Will have to apply this fix to `ILogger` implementations as well then.

Looking closely it seems we currently use the file name by default in the log handlers. Either way having a better derived type name available to the handlers is a good idea.

**Comment by tjvezina** [comment]
Are you saying in this instance, the log context would ideally say:
```
(EntityProxyDataStream<TimerInstance>:33|.ctor) Test
```
or would the generic type name(s) be a separate part? Technically the current context is correct, since it's `FILE:LINE` not `TYPE:LINE`, should that be changed?

**Comment by jkeon** [comment]
Ooops good point. i guess it is working as expected. I forgot that it's the FILE. 

So this issue is specifically for a helper for some Type specific output. The Logger seems to be working as expected and does not need modification.

**Comment by mbaker3** [comment]
Also that the string passed to the log handler's `derivedTypeName` should receive this generic formatting treatment.
For situations where someone has configured their log handler to include that value in the log.

**Comment by tjvezina** [comment]
What namespace would this function (assuming it's a `TypeExtension`) live under? I see `LINQ/LINQExtension` but I don't think `Type/TypeExtension` works.

**Comment by tjvezina** [comment]
An obstacle with using this helper to set `Logger.DerivedTypeName` - the logging system does not reference the rest of Anvil, only vice versa, so there's no way for it to use this extension directly. 🤔

**Comment by mbaker3** [comment]
`Anvil.CSharp.Reflection` seems like an appropriate namespace.
I'm not opposed to putting the logic in `TypeExtension` but I'm not sure how you'd name the method to make it a clear/natural extension method in the API. `.ToNiceName()`?

A `TypeUtil` static class would be fine if this logic doesn't fit well as an extension.

> An obstacle with using this helper to set Logger.DerivedTypeName - the logging system does not reference the rest of Anvil, only vice versa, so there's no way for it to use this extension directly. 

Oof, right. Just duplicate the logic with a comment in both places. Yet another artifact of this hack DLL situation.

**Comment by tjvezina** [comment]
For now I've got `GetReadableName()`, but I'm not married to it. For the namespace I've got `Anvil.CSharp.Types` which isn't great - I could use `.Reflection` but I don't think this extension uses reflection? Does `GetType()` count?

**Comment by mbaker3** [comment]
Technically yea, if you look at what's already in `TypeExtension` it fits along side those methods.
