### ISSUE TITLE
Consolidate the changes in `console-app-changes` with `main`

### ISSUE THREAD

**Issue by mbaker3** [decline-cookies/anvil-csharp-core#66]
When using `anvil-csharp-core` in a pure C# console project a bunch of changes needed to be made to the repo.
Migrate those changes back into `main` in a way that keeps this repo compatible to use within Unity alongside `anvil-unity-core`.

Once this is setup, adjust the CircleCI build scripts the build the project as well.

**Comment by tjvezina** [comment]
Looks like this was resolved in #99?

**Comment by mbaker3** [comment]
Indeed! Thanks.
